Feat/editor schedule manipulation
World-Vision-Clinic/psw-firma1 pull request #146
Opened 2021-12-14 07:17 UTC by p-anja

2021-12-14 08:02 UTC, KristinaStojic requested changes
Rename commits

2021-12-15 12:59 UTC, milica38 approved these changes

2021-12-16 15:33 UTC, milica38 approved these changes

2021-12-27 21:42 UTC, KristinaStojic requested changes
Fix cors problems

2022-01-08 21:16 UTC, closed without merging